export const designTokens = {
  colors: {
    canvasNight: "#000000",
    canvasNightElevated: "#0a0a0a",
    canvasLight: "#ffffff",
    canvasCream: "#fbfbf5",
    ink: "#000000",
    onDark: "#ffffff",
    aloe: "#c1fbd4",
    pistachio: "#d4f9e0",
    hairlineLight: "#e4e4e7",
    hairlineDark: "#1e2c31",
    shade30: "#d4d4d8",
    shade40: "#a1a1aa",
    shade50: "#71717a",
    shade60: "#52525b",
    shade70: "#3f3f46",
  },
  typography: {
    displayFamily: "Inter Display, Inter, Helvetica, Arial, sans-serif",
    bodyFamily: "Inter, Helvetica, Arial, sans-serif",
    monoFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
  },
  radius: {
    xs: "4px",
    md: "8px",
    lg: "12px",
    pill: "9999px",
  },
  spacing: {
    xxs: "2px",
    xs: "4px",
    sm: "8px",
    md: "12px",
    lg: "16px",
    xl: "24px",
    xxl: "32px",
    huge: "64px",
  },
} as const;
